### ISSUE TITLE
Running Deconz Docker on Centos7

### ISSUE THREAD

**Issue by n11111ck** [joch/deconz-docker#1]
Hi!

Thanks for providing the docker image! I'm trying to start this on my CentOS7 machine and got the following problem during startup:

```
docker logs deconz
18:52:22:617 sqlite3_exec SELECT key,value FROM config, error: no such table: config
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
18:52:24:827 CTRL got nwk update id 0
18:52:25:130 CTRL got nwk update id 0
18:52:46:126 void zmController::onApsdeDataIndication(const deCONZ::ApsDataIndication&),3162: assertion 'apsReq.state() == deCONZ::FinishState' failed
18:52:48:379 unhandled APS-DATA.confirm id: 24 status 0xE1
18:53:23:081 CTRL got nwk update id 0
18:53:50:777 unhandled APS-DATA.confirm id: 133 status 0xE1
18:54:23:080 CTRL got nwk update id 0
```

My start command:
`
docker run -d --name="deconz" --net="host" -e TZ="Europe/Zurich" -p 8080:8080/tcp -v "/home/deconz":"/home/deconz":rw --device /dev/zigbee:/dev/zigbee joch/deconz`

Any idea?

**Comment by joch** [comment]
Hello,

The Conbee stick needs to be on `/dev/ttyUSB0` for deconz to work properly, so try using something like this:

```
--device /dev/zigbee:/dev/ttyUSB0
```

I’m planning to update the Docker image to the latest deconz version some time this weekend as well, but that shouldn’t make a difference for the issue you’re having.

**Comment by n11111ck** [comment]
Won't help:

```
[deconz]# docker run -d --name="deconz" --net="host" -e TZ="Europe/Zurich" -p 8080:8080/tcp -v "/home/deconz":"/home/deconz":rw --device /dev/zigbee:/dev/ttyUSB0 joch/deconz
6bba0ae8b3d94a9d7d920bcc5990658e112cb9dd784ec5837cb97719324cf025
[deconz]# docker logs deconz
19:19:19:073 sqlite3_exec SELECT key,value FROM config, error: no such table: config
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
19:19:21:337 CTRL got nwk update id 0
19:19:21:684 CTRL got nwk update id 0

```

**Comment by joch** [comment]
The log isn’t inherently wrong. Have you tried browsing to port 8080?

Also, you need to mount your volume to the proper directory for it to save your config. Something like this:

```
-v "/home/deconz":"/root/.local/share/dresden-elektronik/deCONZ"
```

**Comment by n11111ck** [comment]
now it works! strange!

update would be nice and especially the rest plugin, that would be awesome!

**Comment by joch** [comment]
Great!
